#!/usr/bin/env bash
# Sync the twenty-one JSON Schemas into the Zig binding so they can be
# compiled into the library with @embedFile.
#
#   bash bindings/zig/tools/sync_spec_schema.sh          # copy + regenerate
#   bash bindings/zig/tools/sync_spec_schema.sh --check  # fail on any drift
#
# Why a copy at all: Zig 0.13 refuses `@embedFile` of a path outside the
# module's own directory ("embed of file outside package path"), so the
# library cannot reach up to spec/schema/ at compile time. Every consumer of
# the module therefore needs the schemas beside the sources, exactly as the
# Rust binding keeps bindings/rust/spec_schema/ and the Go binding keeps
# bindings/go/v4/causalontology/spec_schema/.
#
# Nothing here is trusted on faith: the conformance runner re-compares the
# compiled-in bytes against spec/schema/ byte-for-byte whenever a copy of the
# specification is reachable, so drift fails the 137-vector gate.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SRC="${ROOT}/spec/schema"
DST="${ROOT}/bindings/zig/src/spec_schema"
GEN="${ROOT}/bindings/zig/src/spec_schema.zig"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ ! -d "$SRC" ]; then
    echo "no spec/schema at ${SRC}" >&2
    exit 2
fi

mapfile -t FILES < <(cd "$SRC" && ls -1 ./*.schema.json | sed 's|^\./||' | LC_ALL=C sort)
if [ "${#FILES[@]}" -eq 0 ]; then
    echo "no *.schema.json under ${SRC}" >&2
    exit 2
fi

emit_zig() {
    cat <<'HEADER'
//! The Causalontology JSON Schemas, compiled into the library.
//!
//! GENERATED by bindings/zig/tools/sync_spec_schema.sh - do not edit by hand.
//! The bytes are the ones in spec/schema/, copied into src/spec_schema/ only
//! because Zig 0.13 refuses `@embedFile` of a path outside the module
//! directory. schema.zig prefers, in order: an explicit setSpecDir(), the
//! CAUSALONTOLOGY_SPEC environment variable, and otherwise these compiled-in
//! bytes - so a package fetched with `zig fetch` validates with no
//! filesystem, no checkout, and no configuration at all.

const std = @import("std");

pub const Entry = struct {
    /// The bare file name, e.g. "continuant.schema.json".
    name: []const u8,
    /// The schema document, byte-for-byte as it appears in spec/schema/.
    bytes: []const u8,
};

pub const entries = [_]Entry{
HEADER
    for f in "${FILES[@]}"; do
        printf '    .{ .name = "%s", .bytes = @embedFile("spec_schema/%s") },\n' "$f" "$f"
    done
    cat <<'FOOTER'
};

/// How many schemas are compiled in (the specification has twenty-one).
pub const count = entries.len;

/// The compiled-in bytes of one schema file, by bare file name.
pub fn get(name: []const u8) ?[]const u8 {
    for (entries) |e| {
        if (std.mem.eql(u8, e.name, name)) return e.bytes;
    }
    return null;
}

/// Compare the compiled-in copies against a real spec/schema directory,
/// byte-for-byte, in both directions: every compiled-in schema must match
/// its file on disk, and every *.schema.json on disk must be compiled in
/// (so a twenty-second schema cannot appear without this binding noticing).
/// Returns error.SpecSchemaDrift on any mismatch, after describing it.
pub fn checkDrift(a: std.mem.Allocator, dir_path: []const u8, w: anytype) !void {
    var drift = false;
    for (entries) |e| {
        const path = try std.fs.path.join(a, &.{ dir_path, e.name });
        defer a.free(path);
        const on_disk = std.fs.cwd().readFileAlloc(a, path, 1 << 20) catch {
            try w.print("  drift: {s} is compiled in but missing from {s}\n", .{ e.name, dir_path });
            drift = true;
            continue;
        };
        defer a.free(on_disk);
        if (!std.mem.eql(u8, on_disk, e.bytes)) {
            try w.print("  drift: {s} differs from {s} ({d} bytes on disk, {d} compiled in)\n", .{ e.name, dir_path, on_disk.len, e.bytes.len });
            drift = true;
        }
    }
    var dir = std.fs.cwd().openDir(dir_path, .{ .iterate = true }) catch return error.SpecSchemaDirUnreadable;
    defer dir.close();
    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".schema.json")) continue;
        if (get(entry.name) == null) {
            try w.print("  drift: {s} exists in {s} but is not compiled in\n", .{ entry.name, dir_path });
            drift = true;
        }
    }
    if (drift) return error.SpecSchemaDrift;
}
FOOTER
}

if [ "$CHECK" = "1" ]; then
    status=0
    for f in "${FILES[@]}"; do
        if ! cmp -s "${SRC}/${f}" "${DST}/${f}"; then
            echo "drift: bindings/zig/src/spec_schema/${f}" >&2
            status=1
        fi
    done
    for f in $(cd "$DST" 2>/dev/null && ls -1 ./*.schema.json 2>/dev/null | sed 's|^\./||'); do
        if [ ! -f "${SRC}/${f}" ]; then
            echo "stale: bindings/zig/src/spec_schema/${f} has no counterpart in spec/schema" >&2
            status=1
        fi
    done
    if ! emit_zig | cmp -s - "$GEN"; then
        echo "drift: bindings/zig/src/spec_schema.zig is stale" >&2
        status=1
    fi
    [ "$status" = "0" ] && echo "bindings/zig: ${#FILES[@]} compiled-in schemas match spec/schema"
    exit "$status"
fi

mkdir -p "$DST"
for f in $(cd "$DST" 2>/dev/null && ls -1 ./*.schema.json 2>/dev/null | sed 's|^\./||'); do
    [ -f "${SRC}/${f}" ] || rm -f "${DST}/${f}"
done
for f in "${FILES[@]}"; do
    cp "${SRC}/${f}" "${DST}/${f}"
done
emit_zig > "$GEN"
echo "bindings/zig: synced ${#FILES[@]} schemas into src/spec_schema/ and regenerated src/spec_schema.zig"
