//! The Causalontology JSON Schemas, compiled into the library.
//!
//! GENERATED by bindings/zig/tools/sync_spec_schema.sh - do not edit by hand.
//! The bytes are the ones in spec/schema/, copied into src/spec_schema/ only
//! because Zig 0.13 refuses `@embedFile` of a path outside the module
//! directory. schema.zig prefers, in order: an explicit setSpecDir(), the
//! CAUSALONTOLOGY_SPEC environment variable, and otherwise these compiled-in
//! bytes - so a package fetched with `zig fetch` validates with no
//! filesystem, no checkout, and no configuration at all.

const std = @import("std");

pub const Entry = struct {
    /// The bare file name, e.g. "continuant.schema.json".
    name: []const u8,
    /// The schema document, byte-for-byte as it appears in spec/schema/.
    bytes: []const u8,
};

pub const entries = [_]Entry{
    .{ .name = "assertion.schema.json", .bytes = @embedFile("spec_schema/assertion.schema.json") },
    .{ .name = "attitude.schema.json", .bytes = @embedFile("spec_schema/attitude.schema.json") },
    .{ .name = "bridge.schema.json", .bytes = @embedFile("spec_schema/bridge.schema.json") },
    .{ .name = "causal_relation_object.schema.json", .bytes = @embedFile("spec_schema/causal_relation_object.schema.json") },
    .{ .name = "conduit.schema.json", .bytes = @embedFile("spec_schema/conduit.schema.json") },
    .{ .name = "continuant.schema.json", .bytes = @embedFile("spec_schema/continuant.schema.json") },
    .{ .name = "cross_stratal_seam.schema.json", .bytes = @embedFile("spec_schema/cross_stratal_seam.schema.json") },
    .{ .name = "enrichment.schema.json", .bytes = @embedFile("spec_schema/enrichment.schema.json") },
    .{ .name = "individual.schema.json", .bytes = @embedFile("spec_schema/individual.schema.json") },
    .{ .name = "occurrent.schema.json", .bytes = @embedFile("spec_schema/occurrent.schema.json") },
    .{ .name = "port.schema.json", .bytes = @embedFile("spec_schema/port.schema.json") },
    .{ .name = "predicted_occurrence.schema.json", .bytes = @embedFile("spec_schema/predicted_occurrence.schema.json") },
    .{ .name = "prediction_error.schema.json", .bytes = @embedFile("spec_schema/prediction_error.schema.json") },
    .{ .name = "quality.schema.json", .bytes = @embedFile("spec_schema/quality.schema.json") },
    .{ .name = "realizable.schema.json", .bytes = @embedFile("spec_schema/realizable.schema.json") },
    .{ .name = "retraction.schema.json", .bytes = @embedFile("spec_schema/retraction.schema.json") },
    .{ .name = "state.schema.json", .bytes = @embedFile("spec_schema/state.schema.json") },
    .{ .name = "stratum.schema.json", .bytes = @embedFile("spec_schema/stratum.schema.json") },
    .{ .name = "succession.schema.json", .bytes = @embedFile("spec_schema/succession.schema.json") },
    .{ .name = "token.schema.json", .bytes = @embedFile("spec_schema/token.schema.json") },
    .{ .name = "token_causal_claim.schema.json", .bytes = @embedFile("spec_schema/token_causal_claim.schema.json") },
};

/// How many schemas are compiled in (the specification has twenty-one).
pub const count = entries.len;

/// The compiled-in bytes of one schema file, by bare file name.
pub fn get(name: []const u8) ?[]const u8 {
    for (entries) |e| {
        if (std.mem.eql(u8, e.name, name)) return e.bytes;
    }
    return null;
}

/// Compare the compiled-in copies against a real spec/schema directory,
/// byte-for-byte, in both directions: every compiled-in schema must match
/// its file on disk, and every *.schema.json on disk must be compiled in
/// (so a twenty-second schema cannot appear without this binding noticing).
/// Returns error.SpecSchemaDrift on any mismatch, after describing it.
pub fn checkDrift(a: std.mem.Allocator, dir_path: []const u8, w: anytype) !void {
    var drift = false;
    for (entries) |e| {
        const path = try std.fs.path.join(a, &.{ dir_path, e.name });
        defer a.free(path);
        const on_disk = std.fs.cwd().readFileAlloc(a, path, 1 << 20) catch {
            try w.print("  drift: {s} is compiled in but missing from {s}\n", .{ e.name, dir_path });
            drift = true;
            continue;
        };
        defer a.free(on_disk);
        if (!std.mem.eql(u8, on_disk, e.bytes)) {
            try w.print("  drift: {s} differs from {s} ({d} bytes on disk, {d} compiled in)\n", .{ e.name, dir_path, on_disk.len, e.bytes.len });
            drift = true;
        }
    }
    var dir = std.fs.cwd().openDir(dir_path, .{ .iterate = true }) catch return error.SpecSchemaDirUnreadable;
    defer dir.close();
    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".schema.json")) continue;
        if (get(entry.name) == null) {
            try w.print("  drift: {s} exists in {s} but is not compiled in\n", .{ entry.name, dir_path });
            drift = true;
        }
    }
    if (drift) return error.SpecSchemaDrift;
}
